In [1]:
from torch.distributions import Categorical
import torch

/home/tzt/anaconda3/envs/ThinkMatch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [238]:
action_prob = torch.tensor([[0.],[0.1],[0.4],[0.3],[0.7],[0.9]])

In [271]:
dist = torch.distributions.Bernoulli(probs=action_prob)

In [261]:
action = dist.sample()

In [253]:
action

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])

In [272]:
dist.log_prob(action).sum()

tensor(-2.6877)

In [196]:
torch.where((action+1.)/4 > 0.5,1.,0.)

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [257]:
dist.entropy()

tensor([[1.1921e-07],
        [3.2508e-01],
        [6.7301e-01],
        [6.1086e-01],
        [6.1086e-01],
        [3.2508e-01]])

In [62]:
log_prob.sum()

tensor(-1.2324)

In [14]:
torch.log(torch.tensor(0.15))


tensor(-1.8971)

In [63]:
a = torch.tensor(1)

In [64]:
a.item()

1

In [65]:
action

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])

In [68]:
action.sum()

tensor(2.)

In [75]:
action = torch.tensor([[1.3],[1.1],[0.2],[0.3]])

In [74]:
torch.topk(action.view(1,-1),4)[1]

tensor([[0, 1, 3, 2]])

In [77]:
torch.round(action)

tensor([[1.],
        [1.],
        [0.],
        [0.]])

In [80]:
torch.where(action<0.5,1.,0.)

tensor([[0.],
        [0.],
        [1.],
        [1.]])

In [171]:
from datetime import datetime


In [172]:
str(datetime.now())

'2023-10-27 15:15:02.507450'